---

- name: Tenant provisioning starting
  debug:
    msg:
      - "tenant_output_dir:  {{tenant_output_dir}}"
      - "tenant_provisioning_log_file = {{tenant_output_dir}}/{{tenant_provisioning_log_file}}"
      - "tenant_provisioning_results_file = {{tenant_output_dir}}/{{tenant_provisioning_results_file}}"
      - "start and end tenants = {{start_tenant}}  {{end_tenant}}"
      - "create API Gateways for each tenant = {{create_gws_with_each_tenant}}"

- name: Copy tenant provisioning script to known path
  template:
    src: templates/manage_tenants.sh
    dest: /tmp/manage_tenants.sh
    mode: 0755
  vars:
    create_tenants: "true"

- name: Create tenants
  shell: "/tmp/manage_tenants.sh"

- name: Creation of tenants complete
  debug:
    msg: Creation of tenants complete.  output files available at {{tenant_output_dir}}


- name: Tenant Rollout Complete
  debug:
    msg: Tenant Rollout Complete
