---

# Plagarized (and modified for this course) from:  https://github.com/nmasse-itix/OpenShift-Lab/tree/master/roles/3scale
# Thank you nmasse-itix !
#
# Use this ansible play for this course only.
# Afterwards, leverage (and contribute to) the original ansible playbook created by nmasse-itix.

- name: Install xmlstarlet to support mulit-tenant provisioning
  become: true
  yum:
    name: https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/x/xmlstarlet-1.6.1-1.el7.x86_64.rpm
  ignore_errors: yes

- name: check if user is cluster admin
  shell: "oc get project default"
  register: default_project_result
  ignore_errors: true
  changed_when: false

- fail:
    msg: "User does not have cluster-admin rights to install Istio"
  when: default_project_result is failed

- name: check if API Manager deployed
  shell: "oc get project {{ocp_project}}"
  register: api_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{ocp_project}}"
  shell: "oc new-project {{ocp_project}} --display-name={{ocp_project}}"
  when: api_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{ocp_project}} AAD='{{ocp_amp_admin_username}}'"
  when: api_project_result is failed

- name: Make sure we go back do default project
  shell: "oc project default"
  when: api_project_result is failed

################      Multitenent  AMP        #####################

- name: "Make conditional variable based on {{is_shared_cluster}}"
  set_fact:
    threescale_template: "{{threescale_template_shared}}"
  when: is_shared_cluster|bool
- set_fact:
    threescale_template: "{{threescale_template_dedicated}}"
  when: not is_shared_cluster|bool

- name: "Download {{ threescale_template }}"
  get_url:
    url: "{{ threescale_template }}"
    dest: "{{modified_template_path}}"
    force: yes
  when: api_project_result is failed


- name: Process the OpenShift Template and create the OpenShift objects for the 3scale API Management Platform
  shell: |
      oc new-app -f "{{ modified_template_path }}" \
                 -p "MASTER_NAME={{ocp_project}}-master" \
                 -p "MASTER_PASSWORD={{amp_master_passwd}}" \
                 -p "MASTER_ACCESS_TOKEN={{master_access_token}}" \
                 -p "TENANT_NAME={{ocp_project}}" \
                 -p "ADMIN_PASSWORD={{ amp_admin_passwd }}" \
                 -p "WILDCARD_DOMAIN={{ ocp_apps_domain }}" \
                 -n "{{ ocp_project }}" \
                 > {{new_app_output}}
  when: api_project_result is failed

- name: output message
  debug:
    msg: new-app output available at {{new_app_output}}
  when: api_project_result is failed


# #### Storage Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - backend-redis
    - system-memcache
    - system-mysql
    - system-redis
    - zync-database
  when: api_project_result is failed

- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - backend-redis
      - system-memcache
      - system-mysql
      - system-redis
      - zync-database
  when: api_project_result is failed


# #### Backend Listeners
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - backend-listener
    - backend-worker
  when: api_project_result is failed
- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - backend-listener
      - backend-worker
  when: api_project_result is failed

# #### System Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - system-app
  when: api_project_result is failed
- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - system-app
  when: api_project_result is failed

# #### Utility Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - system-resque
    - system-sidekiq
    - system-sphinx
    - backend-cron
  when: api_project_result is failed
- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - system-resque
      - system-sidekiq
      - system-sphinx
      - backend-cron
  when: api_project_result is failed


# #### Gateway Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - apicast-staging
    - apicast-production
    - apicast-wildcard-router
  when: api_project_result is failed
- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - apicast-staging
      - apicast-production
      - apicast-wildcard-router
  when: api_project_result is failed

# #### Zync / RHSSO Sync Tier
- name: "Resume {{with_items}}"
  command: oc rollout resume dc/"{{ item }}" -n "{{ ocp_project }}"
  with_items:
    - zync
  when: api_project_result is failed
- include_tasks: wait_for_deploy.yml
  vars:
    pod_to_wait:
      - zync
  when: api_project_result is failed

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_amp_admin_username}} --overwrite"
###################################################################


- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
